# Project-wide Gradle settings.
# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE are ignored when building from the command line, check
# build.gradle files instead.

# When configured, Gradle will run in incubating parallel mode.
# This option should only be used with decoupled projects. More details, visit
# http://www.gradle.org/guide/performance_tuning#parallel_builds
# org.gradle.parallel=true

# AndroidX package structure to make it easier to support multiple build types
# containing different sets of dependencies and default build configs.
# Please *NOT* move this property inside the parent object in the file, it is important
# to keep Android configuration settings in the top level object.
android.useAndroidX=true

# Kotlin code style for this project: "official" or "obsolete":
kotlin.code.style=official

# Enables namespacing of each library's R class so that its R class includes only the
# resources declared in the library itself and does not include transitive dependencies.
# This property is useful for large projects where each dependency is in its own module,
# but it is less useful for small projects or where you use transitive dependencies.
android.nonTransitiveRClass=true
